CREATE DATABASE CachedPostsDb;
GO

USE CachedPostsDb;
GO

CREATE TABLE Posts
(
    Id INT NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Body NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO